name: doc_route

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: doc1_frontend
    working_dir: /app
    volumes:
      - ../frontend:/app
      - node_modules_cache:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - app_network
    restart:  unless-stopped
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: doc2_backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    networks:
      - app_network
    restart: always
  db:
    image: mariadb:10.6.18
    container_name: doc3_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: doc_route_db
      MARIADB_USER: user
      MARIADB_PASSWORD: userpassword
      TZ: Asia/Manila 
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
  
  localstack:
    image: localstack/localstack:latest   # no custom build needed
    container_name: doc_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
      - DEFAULT_REGION=ap-southeast-1
    volumes:
      - ./localstack_data:/var/lib/localstack
      - ./docker/create-bucket.sh:/etc/localstack/init/ready.d/create-bucket.sh:ro
    networks:
      - app_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: doc_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - app_network   

networks:
  app_network:
    driver: bridge

volumes:
  node_modules_cache:
  db_data:
