name: doc_route

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: doc_frontend
    working_dir: /app
    # volumes:
    #   - ../frontend:/app
    #   - /app/node_modules
    ports:
      - "3000:3000"
    # depends_on:
    #   - backend
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
