name: doc_route

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: doc_frontend
    working_dir: /app
    volumes:
      - ../frontend:/app
      - node_modules_cache:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - app_network
    restart:  unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  node_modules_cache:
